AI_PHRASES = [
    "delve",
    "delve into",
    "nuanced",
    "it's worth noting",
    "it is worth noting",
    "in conclusion",
    "in summary",
    "furthermore",
    "moreover",
    "notably",
    "it's important to note",
    "it is important to note",
    "overall",
    "in the realm of",
    "as previously mentioned",
    "to summarize",
    "comprehensive",
    "multifaceted",
    "in the context of",
    "leverage",
    "utilize",
    "facilitate",
    "paradigm",
    "takeaway",
    "at the end of the day",
    "moving forward",
    "rest assured",
    "commendable",
    "invaluable",
    "undeniable",
    "shed light",
    "underscores",
    "underpin",
    "aligns with",
    "evolving landscape",
    "rapidly evolving",
    "stands at the forefront",
    "in today's world",
    "game-changer",
    "revolutionize",
    "transformative",
    "it is essential to",
    "harnessing",
    "groundbreaking",
    "cutting-edge",
]
